trigger:
  - main

pool:
  vmImage: windows-latest

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '*/surefire-reports/TEST-*.xml'
      goals: 'clean package'

  - script: |
      echo "Listing files in target directory:"
      dir "$(System.DefaultWorkingDirectory)/target"
    displayName: 'Check target directory for JAR'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)/target'
      Contents: '*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

  - script: |
      echo "Listing files in artifact staging directory:"
      dir "$(build.artifactstagingdirectory)"
    displayName: 'Check artifact staging directory for JAR'

  - task: CopyFiles@2
    displayName: 'Copy WAR to Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target'
      Contents: 'maindev-0.0.1-SNAPSHOT.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'maindev-artifact'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Azure Web App'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure for Students (ac9ade9d-773a-4b2c-a1c6-424c1d25234a)'
      appType: 'webApp'
      WebAppName: 'cgenius'
      package: '$(Build.ArtifactStagingDirectory)/maindev-0.0.1-SNAPSHOT.jar'
